load("@io_bazel_rules_d//d:d.bzl", "d_library")

d_library(
    name="asn1",
    srcs=[
        "asn1.d",
        "codec.d",
        "types/alltypes.d",
        "types/identification.d",
        "types/oidtype.d",
        "types/universal/characterstring.d",
        "types/universal/embeddedpdv.d",
        "types/universal/external.d",
        "types/universal/objectidentifier.d",
        "codecs/ber.d"
    ]
)